;; -*- mode: eask; lexical-binding: t -*-

(package "simple-httpd-cli"
         "1.0.0"
         "A command-line interface for simple-httpd")

(website-url "https://github.com/emacs-eine/simple-httpd-cli")
(keywords "convenience")

(package-file "simple-httpd-cli.el")
(files "bin")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)
(source 'jcs-elpa)

(depends-on "emacs" "26.1")
(depends-on "simple-httpd")
(depends-on "commander")
(depends-on "msgu")
